<template>
  <v-container>
    <h1>Welcome to the ___ Experiment!</h1>
    <br>
    <h2>Overview</h2>
    <p>
        This study investigates how people use language to interact on social media, and how well large language models such as chatbots succeed in acting like people. You will see short sequences of a social media post (User A) and a reply (User B). Some of the sequences are based on real human interactions from a social media platform. In others, the User B reply was generated by a chatbot. For each interaction, you will be asked to characterize User B’s response to User A along three scales of 1 to 5.
    </p>
    <br>
    <h2>To participate</h2>  
    <p>If you are interested in participating, please proceed to the next page where we provide information on how we will use the data we collect and ask for your consent. After that, you will have the opportunity to read the instructions and do the task.</p>
    <v-btn color="primary mt-4" @click="next" :disabled="store.pid == null || store.pid == ''">Next
      <v-icon>chevron_right</v-icon></v-btn>
  </v-container>
</template>

<script setup>
import { onMounted } from 'vue';
import { useRouter, useRoute } from 'vue-router'
import { useStore } from "@/stores/store.js"
import Swal from "sweetalert2";
const router = useRouter();
const route = useRoute();
const store = useStore();

onMounted(async () => {
  if (route.query.pid == null || route.query.pid == "") {
    store.pid = null;
    Swal.fire({
      title: 'Missing participant ID',
      icon: 'error',
      text: 'Try reloading the page or contact the experimenter if this error persists.'
    })
    return;
  }

  store.pid = route.query.pid

})

const next = () => {
  router.push("/consent");

}
</script>